version: '3.8'

services:
  api:
    image: node:20-alpine
    container_name: bloodlink-api
    restart: unless-stopped
    working_dir: /app
    environment:
      DATABASE_URL: postgresql://mysqool_user:H8r@9jP!e4Lq2M^zT0wB@core-postgres:5432/bloodlink
      PORT: 8082
      KEYCLOAK_URL: https://keycloak.3olba.com
      KEYCLOAK_REALM: blood-donation
      KEYCLOAK_CLIENT_ID: blood-donation-app
      KEYCLOAK_ADMIN_REALM: blood-donation
      KEYCLOAK_ADMIN_CLIENT_ID: blood-donation-admin
      KEYCLOAK_ADMIN_CLIENT_SECRET: uvp5eBMXAl2pspV8GceswpOAo588KnnT
    ports:
      - "8082:8082"
    volumes:
      - ./backend:/app
    command: sh -c "npm install && node index.js"
    networks:
      - bloodlink-net
      - komptelio-net

networks:
  bloodlink-net:
    driver: bridge
  komptelio-net:
    external: true
    name: shared_net
